insert into Classroom_feature (classroomid, Feature) values (1, 'Camera');
insert into Classroom_feature (classroomid, Feature) values (4, 'Movable Desks');
insert into Classroom_feature (classroomid, Feature) values (15, 'TV');
insert into Classroom_feature (classroomid, Feature) values (2, 'Computer');
insert into Classroom_feature (classroomid, Feature) values (5, 'Lab');
insert into Classroom_feature (classroomid, Feature) values (6, 'Camera');
insert into Classroom_feature (classroomid, Feature) values (10, 'TV');
insert into Classroom_feature (classroomid, Feature) values (8, 'Camera');
insert into Classroom_feature (classroomid, Feature) values (9, 'Camera');
insert into Classroom_feature (classroomid, Feature) values (7, 'TV');
insert into Classroom_feature (classroomid, Feature) values (11, 'Lab');
insert into Classroom_feature (classroomid, Feature) values (12, 'TV');
insert into Classroom_feature (classroomid, Feature) values (16, 'Computer');
insert into Classroom_feature (classroomid, Feature) values (14, 'Camera');
insert into Classroom_feature (classroomid, Feature) values (3, 'Whiteboard');
insert into Classroom_feature (classroomid, Feature) values (13, 'Computer');
