insert into Course (Title, NumOfCreditHours, Subject, Departmentid) values ('Accounting I', 1, 'Math', 2);
insert into Course (Title, NumOfCreditHours, Subject, Departmentid) values ('Intro to Informatics', 2, 'Science', 1);
insert into Course (Title, NumOfCreditHours, Subject, Departmentid) values ('Database Modeling', 4, 'Math', 1);
insert into Course (Title, NumOfCreditHours, Subject, Departmentid) values ('Electricity', 4, 'Science', 4);
insert into Course (Title, NumOfCreditHours, Subject, Departmentid) values ('Into to Psychology', 1, 'Math', 3);
insert into Course (Title, NumOfCreditHours, Subject, Departmentid) values ('Intro to Electricity', 2, 'Science', 4);
insert into Course (Title, NumOfCreditHours, Subject, Departmentid) values ('The Human Mind', 1, 'Math', 3);
insert into Course (Title, NumOfCreditHours, Subject, Departmentid) values ('US History', 1, 'Math', 6);
insert into Course (Title, NumOfCreditHours, Subject, Departmentid) values ('Excel', 4, 'Math', 3);
insert into Course (Title, NumOfCreditHours, Subject, Departmentid) values ('Information Infrastructure I', 1, 'Math', 1);
insert into Course (Title, NumOfCreditHours, Subject, Departmentid) values ('Architecture', 3, 'Science', 4);
insert into Course (Title, NumOfCreditHours, Subject, Departmentid) values ('Animals', 3, 'Science', 5);
insert into Course (Title, NumOfCreditHours, Subject, Departmentid) values ('Plants', 2, 'Math', 5);
insert into Course (Title, NumOfCreditHours, Subject, Departmentid) values ('Business Presentations', 4, 'Science', 2);
insert into Course (Title, NumOfCreditHours, Subject, Departmentid) values ('Building Design', 3, 'Science', 4);
insert into Course (Title, NumOfCreditHours, Subject, Departmentid) values ('Accounting II', 1, 'Math', 2);
insert into Course (Title, NumOfCreditHours, Subject, Departmentid) values ('Intro to Biology ', 1, 'Math', 5);
insert into Course (Title, NumOfCreditHours, Subject, Departmentid) values ('Intro to Coding', 4, 'Math', 4);
insert into Course (Title, NumOfCreditHours, Subject, Departmentid) values ('Information Infrastructure II', 1, 'Math', 1);
insert into Course (Title, NumOfCreditHours, Subject, Departmentid) values ('International Business', 4, 'Math', 2);